# Site settings
title: Sunbird
name: Sunbird
email: info@sunbird.org
description: "Sunbird Site"
environment: production
permalink: pretty
markdown: kramdown
highlighter: pygments
safe: false
ga: UA-106552125-1
anchorPrefix: link
tocTopTag: h2
showToggleButton: true
showSearch: true
  
defaults:
  -
    scope:
      path: "docs"
    values:
      layout: "page"

exclude:
- vendor
- .gitignore
- README.md
- ingredients
- js/components
- js/stores
- js/actions
- js/support
- node_modules
- package.json
- package-lock.json
- node.txt
- Gemfile
- Gemfile.lock
- circle.yml
- s3_website.yml
- staging
- docs/*/ingredients
- docs/*/*.sh
- docs/*/version.yaml
- .sh

sass:
    sass_dir: css
 
