version: 2
jobs:
  review:
    working_directory: /project/workplace/
    docker:
      - image: lakhanmandloi/sunbird-ubuntu-fuller
    steps:
    
      #Checkout
      - checkout
            
      # Run Build command
      - type: shell
        command: |
          if [ "$CIRCLE_BRANCH" != "dev" ]
          then
          echo "baseurl: /pr/$CIRCLE_PR_NUMBER/" >> _config.yml
          echo "buildVersion: PR - $CIRCLE_PR_NUMBER" >> _config.yml
          else
          echo "baseurl: /review/" >> _config.yml
          echo "buildVersion: Commit" >> _config.yml
          fi
          echo "buildNo: $CIRCLE_BUILD_NUM" >> _config.yml
          bundle exec jekyll build 
      # Deploy to s3 bucket
      - type: shell
        command: |
           cd _site
           if [ "$CIRCLE_BRANCH" != "dev" ]
           then
           aws s3 sync --delete . s3://sunbird-docs-qa/pr/$CIRCLE_PR_NUMBER
           prdata=$(curl -X GET -u $guser:x-oauth-basic https://api.github.com/repos/project-sunbird/project-sunbird.github.io/issues/$CIRCLE_PR_NUMBER) 
           username=$(echo "${prdata}" | jq '.user.login')
           contributor=${username//\"/}
           updatedfiles=$(curl -X GET -u $guser:x-oauth-basic https://api.github.com/repos/project-sunbird/project-sunbird.github.io/pulls/$CIRCLE_PR_NUMBER/files)
           updatedfileslist=''
           updatedsectionslist=''
           for row in $(echo "${updatedfiles}" | jq -r '.[] | @base64')
           do  
            _jq() 
            {
             echo ${row} | base64 --decode | jq -r ${1}
            }
            file=$(_jq '.filename')
            echo $file
            if [[ "$file" == pages/* ]] && [[ "$file" == *.md ]]
            then
            filedocs=${file//\.md/}
            filedocs=${filedocs//index/}
            filedocs=${filedocs//.html/}
            filedocs=${filedocs//pages\//}
            url='- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/'$CIRCLE_PR_NUMBER'/'$filedocs' <br /> '
            updatedfileslist=$updatedfileslist$url
            echo $url
            fi
            if [[ "$file" == apis/* ]]
            then
            fileremove=${file##*/}
            echo $fileremove
            fileapi=${file//$fileremove/}
            url='- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/'$CIRCLE_PR_NUMBER'/'$fileapi' <br /> '
            updatedfileslist=$updatedfileslist$url
            echo $url
            fi
            if [[ "$file" == _includes/* ]]
            then
            sections=${file//.html/}
            url='-'$sections' <br /> '
            updatedsectionslist=$updatedsectionslist$url
            fi
           done 
           curl \
              -X POST \
              -u $guser:x-oauth-basic \
              -d '{"body": "Hello @'"$contributor"',<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/'"$CIRCLE_PR_NUMBER"'.<br/> Modified pages are - <br />'"$updatedfileslist"' <br/> Sections modifies are - <br />'"$updatedsectionslist"' "}' \
              https://api.github.com/repos/project-sunbird/project-sunbird.github.io/issues/$CIRCLE_PR_NUMBER/comments
           else
           aws s3 sync --delete . s3://sunbird-docs-qa/review/
           fi
           
  staging:
    working_directory: /project/workplace/
    docker:
      - image: lakhanmandloi/sunbird-ubuntu-fuller
    steps:
    
      #Checkout
      - checkout
            
      # Run Build command
      - type: shell
        command: |
          echo "baseurl: /releases/$CIRCLE_TAG/" >> _config.yml
          echo "buildVersion: $CIRCLE_TAG" >> _config.yml
          echo "buildNo: $CIRCLE_BUILD_NUM" >> _config.yml
          bundle exec jekyll build
          
      # Deploy to s3 bucket
      - type: shell
        command: |
           cd _site
           aws s3 sync --delete . s3://sunbird-docs-qa/releases/$CIRCLE_TAG
          
  prod:
    working_directory: /project/workspace/
    docker:
      - image: lakhanmandloi/sunbird-ubuntu-fuller
    steps:
      
      #Checkout
      - checkout
          
      # Add SSH Key   
      - add_ssh_keys:
          fingerprints:
            - "fa:30:b3:04:87:9f:18:7b:64:47:2f:33:c9:8c:23:7f"
      #Add User
      - type: shell
        command: |
          git config --global user.email "lakhan_m@tekditechnologies.com"
          git config --global user.name "Lakhan Mandloi"
      
      # Pull Code from staging site
      - type: shell
        command: |
          cd ..
          mkdir downloads
          cd downloads
          aws s3 sync --delete s3://sunbird-docs-qa/releases/$CIRCLE_TAG .
           
      # Deploy to Gitpages
      - type: shell
        command: |
          cd ..
          mkdir deploy
          cd deploy
          git clone git@github.com:project-sunbird/project-sunbird.github.io.git
          cd project-sunbird.github.io
          git checkout master
          cp -R .git/ ../
          rm -rf *
          cd ..
          cp -R ../downloads/* project-sunbird.github.io/
          cp -R .git/ project-sunbird.github.io/
          cd project-sunbird.github.io/
          git add -A
          git commit -m "$CIRCLE_TAG"
          git push origin master
          
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - review
      - staging:
          filters:
            tags:
              only: /^release.*/
            branches:
              ignore: /.*/
      - hold:
          type: approval
          requires:
              - staging
          filters:
            tags:
              only: /^release.*/
            branches:
              ignore: /.*/
      - prod:
          requires:
              - hold
          filters:
            tags:
              only: /^release.*/
            branches:
              ignore: /.*/
